### ISSUE TITLE
詳細を決める

### ISSUE THREAD

**Issue by dictav** [NagaokaDevelopersStudy/TDDBC#1]
当面の問題は開催場所や日時など詳細を詰めることです。
まちキャンはすぐに予約でいっぱいになってしまうので、長岡の別の場所、あるいは新潟のほんぽーとでの開催がいいのではないかと思います。
とりあえず、ぼく（@dictav）は使えそうな場所がないか調べ、場所の確保に努めます。
## TODO
- [ ] 会場確保
- [ ] 方針検討
### 長岡市
- まちなかキャンパス
### 新潟市
- ほんぽーと
- クロスパルにいがた
- 新潟国際情報大学の中央キャンパス（たぶん）（要相談）
## 参考
- https://github.com/tddbc/nagaoka-1.0
- [TDDBC長岡1.0](http://devtesting.jp/tddbc/?TDDBC長岡1.0)
- [TDDBC長岡0.1](http://devtesting.jp/tddbc/?TDDBC+長岡+0.1)

**Comment by masaru-b-cl** [comment]
開いたのでクローズ
https://tddbc.connpass.com/event/112293/
